### ISSUE TITLE
Feature wish: Only use the first name if there is no hyphen

### ISSUE THREAD

**Issue by Shen** [liebero3/schildxmllms#2]
Your Script adds all additional names to the username.
Anna Lena Musterfrau Mustermann= anna_lena.musterfrau_mustermann
To have a uniform behavior to Logineo NRW, only the first name should be used if there is no hypen:
Anna Lena Musterfrau Mustermann = anna.musterfrau
Anna-Lena Musterfrau-Mustermann = anna-lena.musterfrau-mustermann

**Comment by liebero3** [comment]
done
